moderation:
  hmd: 'openai/clip-vit-base-patch32'
  threshold: 0.9
ablation:
  combinations:
    "c+v+r": ['claim','verdict','rationale']
    "c+v+iytis": ['claim','verdict','iytis']
    "c+v+r+iytis": ['claim','verdict','rationale','iytis']
    "mi+c+v+r": ['meme_images','claim','verdict','rationale']
    "default": ['meme_images','claim','verdict','iytis', 'title']
    "mi+c+v+r+iytis": ['meme_images','claim','verdict','rationale','iytis']
model_params:
  max_tokens: 1024 # 512 ~ 400 words
baseline:
  num_memes: 1
  model: 'gpt-4o'
  prompt_type: 'zero-shot'
  parse: 'True'
rag:
  num_memes: 7
  model: 'claude-3.5-sonnet'
  prompt_type: 'few-shot'
  parse: 'True'
debate:
  num_memes: 1
  prompt_type: 'few-shot'
  generators: ['claude-3.5-sonnet', 'gemini-1.5-pro']
  evaluators: ['gpt-4o']
  parse: 'False'

# 'gpt-4o', 'gemini-1.5-pro', 'claude-3.5-sonnet', - proprietry models
# 'pixtral-large-2411', 'llama-3.2-90b-vision-instruct', 'qwen-2-vl-72b-instruct', 'qwen/qwq-32b-preview' - open source models
